/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CountiesRouteImport } from './routes/counties'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated.portal'
import { Route as GovernanceIndexRouteImport } from './routes/governance.index'
import { Route as GovernanceSlugRouteImport } from './routes/governance.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CountiesRoute = CountiesRouteImport.update({
  id: '/counties',
  path: '/counties',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const GovernanceIndexRoute = GovernanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GovernanceRoute,
} as any)
const GovernanceSlugRoute = GovernanceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GovernanceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/counties': typeof CountiesRoute
  '/documents': typeof DocumentsRoute
  '/get-involved': typeof GetInvolvedRoute
  '/governance': typeof GovernanceRouteWithChildren
  '/leadership': typeof LeadershipRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/support': typeof SupportRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/governance/$slug': typeof GovernanceSlugRoute
  '/governance/': typeof GovernanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/counties': typeof CountiesRoute
  '/documents': typeof DocumentsRoute
  '/get-involved': typeof GetInvolvedRoute
  '/leadership': typeof LeadershipRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/support': typeof SupportRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/governance/$slug': typeof GovernanceSlugRoute
  '/governance': typeof GovernanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/counties': typeof CountiesRoute
  '/documents': typeof DocumentsRoute
  '/get-involved': typeof GetInvolvedRoute
  '/governance': typeof GovernanceRouteWithChildren
  '/leadership': typeof LeadershipRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/support': typeof SupportRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/governance/$slug': typeof GovernanceSlugRoute
  '/governance/': typeof GovernanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/counties'
    | '/documents'
    | '/get-involved'
    | '/governance'
    | '/leadership'
    | '/news'
    | '/privacy'
    | '/programs'
    | '/support'
    | '/portal'
    | '/governance/$slug'
    | '/governance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/counties'
    | '/documents'
    | '/get-involved'
    | '/leadership'
    | '/news'
    | '/privacy'
    | '/programs'
    | '/support'
    | '/portal'
    | '/governance/$slug'
    | '/governance'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/counties'
    | '/documents'
    | '/get-involved'
    | '/governance'
    | '/leadership'
    | '/news'
    | '/privacy'
    | '/programs'
    | '/support'
    | '/_authenticated/portal'
    | '/governance/$slug'
    | '/governance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CountiesRoute: typeof CountiesRoute
  DocumentsRoute: typeof DocumentsRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  GovernanceRoute: typeof GovernanceRouteWithChildren
  LeadershipRoute: typeof LeadershipRoute
  NewsRoute: typeof NewsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counties': {
      id: '/counties'
      path: '/counties'
      fullPath: '/counties'
      preLoaderRoute: typeof CountiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/governance/': {
      id: '/governance/'
      path: '/'
      fullPath: '/governance/'
      preLoaderRoute: typeof GovernanceIndexRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/governance/$slug': {
      id: '/governance/$slug'
      path: '/$slug'
      fullPath: '/governance/$slug'
      preLoaderRoute: typeof GovernanceSlugRouteImport
      parentRoute: typeof GovernanceRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GovernanceRouteChildren {
  GovernanceSlugRoute: typeof GovernanceSlugRoute
  GovernanceIndexRoute: typeof GovernanceIndexRoute
}

const GovernanceRouteChildren: GovernanceRouteChildren = {
  GovernanceSlugRoute: GovernanceSlugRoute,
  GovernanceIndexRoute: GovernanceIndexRoute,
}

const GovernanceRouteWithChildren = GovernanceRoute._addFileChildren(
  GovernanceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CountiesRoute: CountiesRoute,
  DocumentsRoute: DocumentsRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  GovernanceRoute: GovernanceRouteWithChildren,
  LeadershipRoute: LeadershipRoute,
  NewsRoute: NewsRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
